### PR TITLE
Footer adjustments

### LINKED ISSUE #123: two non-urgent footer requests
1. Can we swap the logo in the footer with the fuller logo, the version that also says "Smitten Kitchen" underneath. It felt too cluttered for the top of the page, but should work well there. [If this is something I can do on my own, let me know and I'm happy to. It said something like "svg file" in the module and I wasn't sure what that was.]
2. Can we add a back to top button?

### PR DESCRIPTION
**Pull request by sarahmonster**
This does two things:

- Adds the "smitten kitchen" text to the logo in the footer only—this is accomplished by adding the logo text to the SVG file, then hiding it in the header (and adjusting the sizing and spacing so the header looks as it did originally.)

- Adds a "back to top" arrow-link to the bottom right-hand corner. It's deliberately super-subtle, and doesn't appear until you're a little ways down the page. 

Fixes #123.

### CODE REVIEW

**Comment by michiecat** [comment]
@sarahmonster I'm seeing the text inside the logo in the footer. However, on shorter pages that don't have as much content, the footer area flickers after you scroll down a bit. Strangely it flickers for a while, but if you scroll up and down repeatedly, the footer suddenly starts to behave itself. I only noticed this behavior in Chrome (it didn't occur when I tested in Firefox). The gif below didn't really capture the flickering behavior (but imagine the entire footer area flickering in and out during the part where I'm scrolling slightly up and down at the bottom.

smitten-kitchen-scrolling

**Comment by michiecat** [comment]
Otherwise the arrow is working as intended.

**Comment by sarahmonster** [comment]
I'm having a bit of trouble reproducing—was just wondering if this is happening on the live site as well? My guess is that it's related to the sticky ad in the sidebar and a separate issue not related to these changes—I'm seeing something that might be similar here, for instance: https://smittenkitchen.com/contact/

**Comment by debperelman** [comment]
Do I need to okay this or are we good to go? Thanks.

**Comment by sarahmonster** [comment]
I'm going to go ahead and merge it. If there are any issues please do feel free to open a new issue!

**Pull request merged**
