### PR TITLE
Add a footer to posts on the front page. 

### LINKED ISSUE #135: we could use a footer on posts that show on the front page
Because I show more than one photo from the top (newest) post (and adjust the break after I publish the next new article), it's a little confusing when scrolling down the front page to figure out where one post ends and the next one begins -- the only way a reader can tell is the small tag over the top photo and then the large title underneath it (but at that point, they've already scrolled past the lead photo). The solution would be to create a small footer below each post. 

I'm wondering if it could just mimic the footer on the full post pages (see attached but specifically just one subtle dashed line and one line of information in that small all-caps font)... and here's where it gets messier, which is that this seems to be an ideal place to also move the date down from under the title, just to reduce the visual clutter and empty spaces on the front page. However, on individual posts, it makes sense to keep it there (because there are also the essential "jump to recipe, comments" links. Do you think it's okay if the location of the dates on the front page don't match the location of the dates on the individual pages?
screen shot 2016-08-03 at 2 41 50 pm

I think we'll have enough space on this footer line to add other information, maybe either a comment count (used to have this), social media icons or those jump to recipes/comments links.

### PR DESCRIPTION
**Pull request by sarahmonster**
Fixes #135 when merged. Looks something like this:
screenshot 2016-11-18 14 36 37

### CODE REVIEW

**Comment by debperelman** [comment]
This looks good but it's unclear to me whether the footer is bold (I'd prefer it is not). Is it possible to add more information to the line such as the social media icons or more category listings?

**Comment by sarahmonster** [comment]
The fonts just turn out a bit bolder on my test site—it's styled the same way as the regular post footers.

We could add more information here if you'd like. I'd recommend against social media sharing icons. These make sense on the full post, but don't make sense on an excerpt—you'd want to read the full post before sharing it. On top of that, sharing icons are pretty high-stress in terms of performance—each one is loading a bunch of stuff from another website—so having lots of them on a page can really slow your load time.

We could add categories here if you'd like, but given that most posts have quite a lot of categories (for example on a recent post: "Breakfast, Casserole, Lunch, Photo, Picnics, Spinach, Tarts/Quiche, Vegetarian, Weeknight Favorite") adding them definitely means the footer would span two lines. If that's okay I can update this—just let me know!

**Comment by debperelman** [comment]
Thanks -- would you mind showing me a preview? Maybe if we kept the font small and light, it wouldn't be too obtrusive. I like the idea of giving people a chance to jump straight to the categories from the post.

**Comment by sarahmonster** [comment]
For sure!
screenshot 2016-12-07 17 31 53

We could also try moving them to their own line, so the comments don't get engulfed quite so much:
screenshot 2016-12-07 17 33 20

OR we could try making them grey so they comment link still stands out, but that may be iffy from a usability standpoint:
screenshot 2016-12-07 17 35 55

**Comment by sarahmonster** [comment]
For sure!
screenshot 2016-12-07 17 31 53

We could also try moving them to their own line, so the comments don't get engulfed quite so much:
screenshot 2016-12-07 17 33 20

OR we could try making them grey so they comment link still stands out, but that may be iffy from a usability standpoint:
screenshot 2016-12-07 17 35 55

**Comment by sarahmonster** [comment]
@debperelman What are your thoughts on this? It'd be lovely to get it merged in.

**Comment by debperelman** [comment]
I like the listing of categories in the same line, even if it spills to two, but instead of writing "LEAVE A COMMENT" can we say "READ COMMENTS" or "SEE COMMENTS" or "# COMMENTS" with the number to date. (I feel like we should gently discourage leaving comments before reading the post, hoping against hope...) Thank you.

**Comment by sarahmonster** [comment]
"Leave a comment" will only appear if there are no comments—otherwise it will say "x comments". "Read comments" wouldn't make much sense if there weren't any yet! I've updated it so that it now reads "No comments" instead of "Leave a comment" which is probably the best solution here.

I'm going to merge this in no and add it to the production site—do let us know if there are any issues!

**Pull request merged**
